feat: Output of all information required by federated results
team-emb4/sched_sim_rust pull request #19
Opened 2023-05-17 08:58 UTC by kobayu858

###SUMMARY
- Output of all information required by federated results.
- DAG Information
 - Total utilization
 - Critical path length, deadline, and total workload for each DAG
- Processor Information
 - Total number of cores
- Result details
 - Scheduling success or failure
 - (in case of scheduling success)
  - Number of cores used by high utilization tasks
  - Number of cores used by underutilized tasks
 - (in case of scheduling failure)
 - Reason
 - Number of underutilized cores

2023-05-17 22:54 UTC, atsushi421 requested changes

2023-05-17 22:54 UTC, atsushi421 commented on lib/src/output_log.rs
> +struct CoreInfo {
```suggestion
struct ProcessorInfo {
```

2023-05-17 22:54 UTC, atsushi421 commented on lib/src/output_log.rs
> +        .expect("Failed to serialize DAGSetInfo to YAML");
nits

2023-05-17 22:54 UTC, atsushi421 commented on lib/src/output_log.rs
> +pub fn dump_number_of_cores_to_yaml(file_path: &str, number_of_cores: usize) {
```suggestion
pub fn dump_processor_info_to_yaml(file_path: &str, number_of_cores: usize) {
```

2023-05-17 22:54 UTC, atsushi421 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    };
```suggestion
    let result_info = ResultInfo { result };
```

2023-05-17 23:35 UTC, kobayu858 commented on lib/src/output_log.rs
> +struct CoreInfo {
CoreInfo -> ProcessorInfo

2023-05-17 23:35 UTC, kobayu858 commented on lib/src/output_log.rs
> +        .expect("Failed to serialize DAGSetInfo to YAML");
CoreInfo -> ProcessorInfo

2023-05-17 23:37 UTC, kobayu858 commented on lib/src/output_log.rs
> +        .expect("Failed to serialize DAGSetInfo to YAML");
DAGSetInfo -> ProcessorInfo

2023-05-17 23:38 UTC, kobayu858 commented on lib/src/output_log.rs
> +pub fn dump_number_of_cores_to_yaml(file_path: &str, number_of_cores: usize) {
dump_number_of_cores_to_yaml -> dump_processor_info_to_yaml

2023-05-17 23:40 UTC, kobayu858 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    };
accept your suggestion

2023-05-18 01:29 UTC, atsushi421 requested changes

2023-05-18 01:29 UTC, atsushi421 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    fn test_dump_federated_info_normal() {
Rename

2023-05-18 01:29 UTC, atsushi421 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    fn test_dump_federated_lack_cores_for_high_tasks() {
Rename

2023-05-18 01:29 UTC, atsushi421 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    fn test_dump_federated_lack_cores_for_low_tasks() {
Rename

2023-05-18 01:29 UTC, atsushi421 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    fn test_dump_federated_unsuited_tasks() {
Rename

2023-05-18 01:29 UTC, atsushi421 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +
```suggestion
```

2023-05-18 01:29 UTC, atsushi421 commented on lib/src/output_log.rs
> +    fn test_dump_number_of_cores_info_to_yaml() {
Rename

2023-05-18 03:06 UTC, kobayu858 commented on 2014_RTSS_federated_original/src/outputs_result.rs
> +    fn test_dump_federated_lack_cores_for_high_tasks() {
rename

2023-05-18 03:22 UTC, atsushi421 approved these changes
LGTM!

2023-05-18 03:22 UTC, merged