feat: return_allocated_node_data
team-emb4/sched_sim_rust pull request #71
Opened 2023-07-12 10:45 UTC by kobayu858

## Description

- Return_allocated_node_data
- For preemptive scheduler

## Related links

None.

## Pre-review checklist for the PR author

- [x] I've confirmed the [self-checklist](https://docs.google.com/spreadsheets/d/1p5KMcm752iCySHJz0xL1qf6fcLDKprbo/edit#gid=863618628).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-07-12 12:07 UTC, atsushi421 requested changes

2023-07-12 12:07 UTC, atsushi421 commented on lib/src/core.rs
> +    pub fn return_allocated_node_data(&mut self) -> Option<NodeData> {
How about `suspend_execution` ?

2023-07-12 12:07 UTC, atsushi421 commented on lib/src/homogeneous.rs
> +    fn return_allocated_node_data(&mut self, core_id: usize) -> Option<NodeData> {
See above.

2023-07-12 23:26 UTC, kobayu858 commented on lib/src/core.rs
> +    pub fn return_allocated_node_data(&mut self) -> Option<NodeData> {
Changed.

2023-07-12 23:26 UTC, kobayu858 commented on lib/src/homogeneous.rs
> +    fn return_allocated_node_data(&mut self, core_id: usize) -> Option<NodeData> {
Changed.

2023-07-13 00:23 UTC, atsushi421 approved these changes
LGTM

2023-07-13 00:23 UTC, merged