feat; decompose
team-emb4/sched_sim_rust pull request #72
Opened 2023-07-13 06:40 UTC by kobayu858

## Description

- Computation of node deadlines for decomposition-based scheduler

## Related links

- original paper [OPEN_LINK](https://drive.google.com/file/d/1YH-MAWsw1VAvxqco4Beg3njQ9ykG-sb-/view?usp=drive_link) p5, p6
- paper summary [EmbIV_INTERNAL_LINK](https://docs.google.com/presentation/d/1rabhhA9ziIcBjvT8XPLue78XEWcKMvH4/edit?usp=drive_link&ouid=114908281052440997053&rtpof=true&sd=true) p27 - p34
- design specifications [EmbIV INTERNAL LINK](https://docs.google.com/presentation/d/14YO4wHY1QqGOjoY9_g4djvtTaBXV0RCj/edit?usp=drive_link&ouid=114908281052440997053&rtpof=true&sd=true) p4, p5

## Pre-review checklist for the PR author

- [x] I've confirmed the [self-checklist](https://docs.google.com/spreadsheets/d/1p5KMcm752iCySHJz0xL1qf6fcLDKprbo/edit#gid=863618628).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-07-14 22:45 UTC, atsushi421 requested changes

2023-07-14 22:45 UTC, atsushi421 commented on 2014_TPDS_basic_decomposition_based_algorithm/src/decomposition.rs
> +        let decimal_part_str = rounded_node_deadline
```suggestion
        let fractional_part_str = rounded_node_deadline
```

2023-07-14 22:45 UTC, atsushi421 commented on 2014_TPDS_basic_decomposition_based_algorithm/src/decomposition.rs
> +        }
This process is not performed very often and can be deleted.

2023-07-14 22:45 UTC, atsushi421 commented on 2014_TPDS_basic_decomposition_based_algorithm/src/decomposition.rs
> +            "deadline",
```suggestion
            "integer_scaled_deadline",
```

2023-07-18 01:44 UTC, kobayu858 commented on 2014_TPDS_basic_decomposition_based_algorithm/src/decomposition.rs
> +        let decimal_part_str = rounded_node_deadline
Fixed.

2023-07-18 01:45 UTC, kobayu858 commented on 2014_TPDS_basic_decomposition_based_algorithm/src/decomposition.rs
> +            "deadline",
Changed.

2023-07-18 06:00 UTC, atsushi421 approved these changes
LGTM

2023-07-18 06:00 UTC, merged