refactor: Method of determining schedulability
team-emb4/sched_sim_rust pull request #82
Opened 2023-08-03 07:24 UTC by kobayu858

## Description

- Changed the decision as follows
　- `Finish time <= Period * (Number of releases + 1)` when ture.
　- Each information is taken from a log file.
- It does not determine which DAG caused the deadline miss.
- Simply determine if the schedule succeeded
- 
## Related links

None.

## Pre-review checklist for the PR author

- [x] I've confirmed the [self-checklist](https://docs.google.com/spreadsheets/d/1p5KMcm752iCySHJz0xL1qf6fcLDKprbo/edit#gid=863618628).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-08-08 21:04 UTC, atsushi421 requested changes

2023-08-08 21:04 UTC, atsushi421 commented on 2021_RTCSA_dynfed/src/main.rs
> +    }
```suggestion
    for dag in dag_set {
        if !result {
            break; // If result is already false, no need to check further.
        }
        result = result
            && dag_set_log[dag.get_dag_id()]["worst_response_time"]
                .as_i64()
                .unwrap()
                <= dag.get_head_period().unwrap() as i64;
    }
```

2023-08-09 02:27 UTC, kobayu858 commented on 2021_RTCSA_dynfed/src/main.rs
> +    }
Thank you very much. Fixed.

2023-08-09 02:30 UTC, atsushi421 approved these changes
LGTM

2023-08-09 02:30 UTC, merged