refactor: write core processing log
team-emb4/sched_sim_rust pull request #89
Opened 2023-08-18 12:02 UTC by kobayu858

## Description

- Changed core log execution time writing
- Increase execution time of cores other than Idle by 1 immediately after `process()`
- This will support preemptives.

## Related links

None.

## Pre-review checklist for the PR author

- [x] I've confirmed the [self-checklist](https://docs.google.com/spreadsheets/d/1p5KMcm752iCySHJz0xL1qf6fcLDKprbo/edit#gid=863618628).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-08-18 21:53 UTC, atsushi421 requested changes

2023-08-18 21:53 UTC, atsushi421 commented on lib/src/util.rs
> +            }
```suggestion
            match result {
            // If the result matches Continue, return the index
            ProcessResult::Continue => Some(index),
            // If the result is Done and does not contain the "dummy" key, return the index
            ProcessResult::Done(node_data) if !node_data.params.contains_key("dummy") => Some(index),
            // For all other cases, return None
            _ => None,
        }
```

2023-08-21 02:43 UTC, kobayu858 commented on lib/src/util.rs
> +            }
Changed.

2023-08-21 03:17 UTC, atsushi421 approved these changes
LGTM

2023-08-21 03:17 UTC, merged